name: Run Tests
##
# This github workflow is used to run tests on all commits to all branches
##

on:
  push
  #push:
  #  branches:
  #    - master

jobs:

  docs:
    name: Build Docs

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: sudo apt-get install -y mkdocs

      - name: Build Documentation
        run: make docsite

  tests:
    name: Unit Tests

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install -y golang libgl1-mesa-dev xorg-dev libxkbcommon-dev go-staticcheck

      - name: Run Tests
        run: make test
